services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    tty: true # Manter o tty ativo para evitar que o container feche prematuramente

  tailwind:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rails
    command: ["./bin/rails", "tailwindcss:watch", "always"] # Usando o argumento 'always' para manter o processo vivo
    tty: true
