services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  db_data:
